-- Complète la migration précédente : `id` devient une vraie clé technique
-- auto-générée (les Edge Functions n'ont plus besoin de fournir un id —
-- seulement sport + external_id, sur lesquels porte la contrainte unique).
alter table public.matches_cache alter column id add generated by default as identity;

-- Démarre la séquence bien au-dessus des id existants pour ne jamais
-- entrer en conflit avec les lignes déjà présentes.
select setval(
  pg_get_serial_sequence('public.matches_cache', 'id'),
  (select coalesce(max(id), 0) + 1000000 from public.matches_cache),
  false
);
